# Generated by Django 3.2.5 on 2021-07-21 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=30, verbose_name='ユーザーid')),
                ('password', models.CharField(max_length=15, verbose_name='パスワード')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
