# Generated by Django 3.2.5 on 2021-07-22 10:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, verbose_name='テキスト名')),
                ('time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxLengthValidator(1440)], verbose_name='勉強時間')),
                ('category', models.CharField(max_length=20, verbose_name='分類')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
