# Generated by Django 3.2.5 on 2021-07-27 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_studytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='ユーザーid')),
                ('password', models.CharField(max_length=15, verbose_name='パスワード')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='studytime',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.userdata'),
        ),
    ]
