# Generated by Django 3.2.5 on 2021-07-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210727_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=30, verbose_name='サイト名')),
                ('category', models.CharField(max_length=30, verbose_name='分類')),
                ('auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.userdata')),
            ],
        ),
    ]
