# Generated by Django 3.2.5 on 2021-08-15 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210813_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='registsite',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studytime',
            name='regist_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
